name: Validate

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    uses: dornglut/github-workflows/.github/workflows/reusable-python-repository-validate.yml@3cc9ad6c9bde3b970695baefa1cd815ff56111c7
