name: Validate

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    uses: dornglut/github-workflows/.github/workflows/reusable-python-repository-validate.yml@b6caad377102ca73794efaf734a65903b8efa829
